export const SESSION_EXPIRY_MINUTES = 30;
export const GEO_CACHE_TTL_MS = 60 * 60 * 1000;
export const GEO_CACHE_MAX_SIZE = 1000;

export const RATE_LIMIT_MAX_REQUESTS = 100;
export const RATE_LIMIT_WINDOW_MS = 60 * 1000;

export const MAX_DATE_RANGE_DAYS = 365;

export const VALID_EVENT_TYPES = ['pageview', 'custom', 'identify', 'heartbeat'] as const;

// Country names validated against ipwho.is and ip-api.com geo-IP providers
export const COUNTRY_OPTIONS = [
	'Afghanistan',
	'Albania',
	'Algeria',
	'Andorra',
	'Angola',
	'Argentina',
	'Armenia',
	'Australia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize',
	'Benin',
	'Bhutan',
	'Bolivia',
	'Bosnia and Herzegovina',
	'Botswana',
	'Brazil',
	'Brunei',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Cape Verde',
	'Central African Republic',
	'Chad',
	'Chile',
	'China',
	'Colombia',
	'Comoros',
	'Congo',
	'Costa Rica',
	'Croatia',
	'Cuba',
	'Cyprus',
	'Czech Republic',
	'Denmark',
	'Djibouti',
	'Dominican Republic',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Eritrea',
	'Estonia',
	'Eswatini',
	'Ethiopia',
	'Fiji',
	'Finland',
	'France',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany',
	'Ghana',
	'Greece',
	'Guatemala',
	'Guinea',
	'Guyana',
	'Haiti',
	'Honduras',
	'Hungary',
	'Iceland',
	'India',
	'Indonesia',
	'Iran',
	'Iraq',
	'Ireland',
	'Israel',
	'Italy',
	'Jamaica',
	'Japan',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Kuwait',
	'Kyrgyzstan',
	'Laos',
	'Latvia',
	'Lebanon',
	'Lesotho',
	'Liberia',
	'Libya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives',
	'Mali',
	'Malta',
	'Mauritania',
	'Mauritius',
	'Mexico',
	'Moldova',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Morocco',
	'Mozambique',
	'Myanmar',
	'Namibia',
	'Nepal',
	'Netherlands',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'North Korea',
	'North Macedonia',
	'Norway',
	'Oman',
	'Pakistan',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Poland',
	'Portugal',
	'Qatar',
	'Romania',
	'Russia',
	'Rwanda',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Sierra Leone',
	'Singapore',
	'Slovakia',
	'Slovenia',
	'Somalia',
	'South Africa',
	'South Korea',
	'South Sudan',
	'Spain',
	'Sri Lanka',
	'Sudan',
	'Suriname',
	'Sweden',
	'Switzerland',
	'Syria',
	'Taiwan',
	'Tajikistan',
	'Tanzania',
	'Thailand',
	'Timor-Leste',
	'Togo',
	'Trinidad and Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'United Kingdom',
	'United States',
	'Uruguay',
	'Uzbekistan',
	'Venezuela',
	'Vietnam',
	'Yemen',
	'Zambia',
	'Zimbabwe'
] as const;

export const SEARCH_ENGINES = ['google', 'bing', 'yahoo', 'duckduckgo', 'baidu', 'yandex', 'ask', 'aol', 'ecosia'];

export const SOCIAL_NETWORKS = [
	'facebook',
	'twitter',
	'x.com',
	'instagram',
	'linkedin',
	'tiktok',
	'pinterest',
	'reddit',
	'youtube',
	'tumblr',
	'snapchat',
	'whatsapp',
	'telegram',
	'discord',
	'twitch',
	'vk',
	'weibo',
	'mastodon',
	'threads'
];

export const TIMEZONES = [
	'UTC',
	'Pacific/Honolulu',
	'America/Anchorage',
	'America/Los_Angeles',
	'America/Denver',
	'America/Chicago',
	'America/New_York',
	'America/Toronto',
	'America/Vancouver',
	'America/Mexico_City',
	'America/Bogota',
	'America/Lima',
	'America/Santiago',
	'America/Sao_Paulo',
	'America/Buenos_Aires',
	'Atlantic/Reykjavik',
	'Europe/London',
	'Europe/Dublin',
	'Europe/Lisbon',
	'Europe/Paris',
	'Europe/Berlin',
	'Europe/Brussels',
	'Europe/Amsterdam',
	'Europe/Rome',
	'Europe/Madrid',
	'Europe/Athens',
	'Europe/Bucharest',
	'Europe/Moscow',
	'Africa/Lagos',
	'Africa/Cairo',
	'Africa/Johannesburg',
	'Asia/Dubai',
	'Asia/Tehran',
	'Asia/Karachi',
	'Asia/Mumbai',
	'Asia/Kolkata',
	'Asia/Bangkok',
	'Asia/Singapore',
	'Asia/Hong_Kong',
	'Asia/Shanghai',
	'Asia/Seoul',
	'Asia/Tokyo',
	'Australia/Perth',
	'Australia/Adelaide',
	'Australia/Sydney',
	'Australia/Brisbane',
	'Pacific/Auckland'
] as const;

export const MAX_STRING_LENGTHS = {
	websiteId: 36,
	domain: 255,
	href: 2048,
	referrer: 2048,
	visitorId: 36,
	sessionId: 36,
	language: 50,
	timezone: 100,
	browser: 50,
	browserVersion: 20,
	os: 50,
	osVersion: 20,
	deviceType: 20,
	title: 500,
	eventName: 255,
	filterValue: 100
} as const;

export const DEFAULT_QUERY_LIMITS = {
	pageviews: 10000,
	visitors: 5000,
	sessions: 500,
	events: 50,
	metrics: 100
} as const;
