export const generateVisitorName = (id: string) => {
	const adjectives = [
		'Happy',
		'Lucky',
		'Sunny',
		'Clever',
		'Brave',
		'Calm',
		'Eager',
		'Fancy',
		'Gentle',
		'Jolly',
		'Swift',
		'Bright',
		'Mighty',
		'Silent',
		'Wild',
		'Cosmic',
		'Crystal',
		'Daring',
		'Electric',
		'Fluffy',
		'Golden',
		'Hidden',
		'Icy',
		'Jade',
		'Kind',
		'Lunar',
		'Magic',
		'Noble',
		'Ocean',
		'Purple',
		'Quiet',
		'Radiant',
		'Silver',
		'Thunder',
		'Urban',
		'Vivid',
		'Witty',
		'Young',
		'Zesty',
		'Azure'
	];
	const animals = [
		'Panda',
		'Tiger',
		'Lion',
		'Eagle',
		'Dolphin',
		'Fox',
		'Wolf',
		'Bear',
		'Hawk',
		'Owl',
		'Shark',
		'Whale',
		'Dragon',
		'Phoenix',
		'Raven',
		'Falcon',
		'Lynx',
		'Panther',
		'Cheetah',
		'Leopard',
		'Jaguar',
		'Puma',
		'Moose',
		'Elk',
		'Bison',
		'Coyote',
		'Jackal',
		'Hyena',
		'Otter',
		'Beaver',
		'Badger',
		'Raccoon',
		'Squirrel',
		'Rabbit',
		'Hare',
		'Deer',
		'Stag',
		'Mantis',
		'Cobra',
		'Viper'
	];
	let hash = 0;
	for (let i = 0; i < id.length; i++) {
		hash = id.charCodeAt(i) + ((hash << 5) - hash);
	}
	const adj = adjectives[Math.abs(hash) % adjectives.length];
	const animal = animals[Math.abs(hash >> 5) % animals.length];
	return `${adj} ${animal}`;
};

export const generateAvatarUrl = (id: string) => `https://api.dicebear.com/9.x/adventurer/svg?seed=${id}`;
